config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'hoges/index'
  get 'hoges/new'
  post 'hoges/create',as:"hoges"
  get 'hoges/:id' => 'hoges#show', as: 'hoge'
  get 'likes/create'
  get 'likes/destroy'
  get 'sessions/new'
  get 'users/new'
  get 'persons/new'
  root 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get 'microposts/index'
  resources :microposts do
    resources :comments, only: [:create]
  end
  get '/posts' => 'post#index'
  get 'posts/index'
  get '/signup' => 'users#new'
  post '/singup' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :microposts, only:[:create, :destroy]
  resources :relationships, only:[:create,:destroy]
  resources :likes, only: [:create, :destroy]
end 

app/models/hoge.rb
class Hoge < ApplicationRecord
  validates :name, presence: true
  validates :content, presence: true
end

app/controllers/hoges_controller.rb
class HogesController < ApplicationController
  def index
    @hoges = Hoge.all
  end

  def show
    @hoge = Hoge.find(params[:id])
  end

  def new
    @hoge = Hoge.new
  end

  def create
    @hoge = Hoge.new(hoges_params)
    if @hoge.save
      flash[:hoge] = "投稿完了！"
      redirect_to :action => "index"
    else
      render :action => "new"
    end
  end

  def hoges_params
    params.require(:hoge).permit(:name, :content)
  end
end

app/helpers/hoges_helper.rb
module HogesHelper
end

app/views/hoges/index.html.erb
<h1>投稿一覧</h1>
<%= flash[:hoge] %>
<% @hoges.each do |hoge| %>
  <%= hoge.name%>
  <%= hoge.content %>
  <%= link_to  "詳細", hoge_path(hoge)%><br>
<% end %>
<%= link_to  "データを追加", hoges_new_path %>

app/views/hoges/new.html.erb
<h1>Hoges#new</h1>
<p>Find me in app/views/hoges/new.html.erb</p>

<%= form_for(@hoge) do |f| %>
  <%= f.label :名前 %>
  <%= f.text_field :name %>
  <%= f.label :内容 %>
  <%= f.text_area :content %>
  <%= f.submit "送信" %>
<% end %>

app/views/hoges/show.html.erb
<%= @hoge.content %>
<%= link_to  "戻る", hoges_index_path %>