config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'hoges/index'
  get 'hoges/new'
  post 'hoges/create',as:"hoges"
  get 'hoges/:id' => 'hoges#show', as: 'hoge'
  get 'likes/create'
  get 'likes/destroy'
  get 'sessions/new'
  get 'users/new'
  get 'persons/new'
  root 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get 'microposts/index'
  resources :microposts do
    resources :comments, only: [:create]
  end
  get '/posts' => 'post#index'
  get 'posts/index'
  get '/signup' => 'users#new'
  post '/singup' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :microposts, only:[:create, :destroy]
  resources :relationships, only:[:create,:destroy]
  resources :likes, only: [:create, :destroy]
end 

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate :picture_size
  has_many :likes, dependent: :destroy
  has_many :iine_users, through: :likes, source: :user
  has_many :comments

  def iine(user)
    likes.create(user_id: user.id)
  end

  def uniine(user)
    likes.find_by(user_id: user.id).destroy
  end

  def iine?(user)
    iine_users.include?(user)
  end

  private

    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user, only: :destroy

    def index
      @microposts = Micropost.all
    end

    def create
      @micropost = current_user.microposts.build(micropost_params)
      if @micropost.save 
        flash[:success] = "Micropost created!"
        redirect_to root_url
      else
        q = Micropost.none.ransack
        @feed_items = []
        render 'static_pages/home'
      end
    end

    def show
      @micropost = Micropost.find(params[:id])
      @comments = @micropost.comments
      @comment = Comment.new
    end

    def edit
      @micropost = Micropost.find(params[:id])
    end

    def update
      @micropost = Micropost.find(params[:id])
      if @micropost.update_attributes(micropost_params)
        redirect_to micropost_path
        flash[:success] = "変更完了！"
      else
        render 'edit'
      end
    end


    def destroy
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        redirect_to root_url
    end

    def micropost_params
        params.require(:micropost).permit(:content,:picture)
    end

    def correct_user
        @micropost = current_user.microposts.find_by(id:params[:id])
        redirect_to root_url if @micropost.nil?
    end

  private
  
    def micropost_params
      params.require(:micropost).permit(:content)
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
  <%= link_to micropost_path(micropost) do %>
  <%= micropost.content %>
  <%= image_tag micropost.picture.url if micropost.picture? %><br>
  <% end %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to  "delete",micropost, method: :delete,
                            data:{ confirm: "You sure?" } %>
    <% end %>
  </span>
  <%= render  "likes/like", micropost: micropost %>
</li>

app/views/microposts/edit.html.erb
<% provide(:title, "Edit micropost") %>
<h1>投稿編集</h1>
<%= @micropost.content %>

<%= form_for(@micropost) do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit "変更完了" %>
<% end %>

app/views/microposts/index.html.erb
<% @microposts.each do |micropost| %>
  <%= micropost.content %>　　　
  <%= micropost.user.name %><br>
<% end %>

app/views/microposts/show.html.erb
<%= @micropost.user.name %><br>
<%= @micropost.content %>
<%= link_to  "戻る", root_path %>
<% if current_user.id == @micropost.user_id %>
  <%= link_to  "編集", edit_micropost_path(@micropost) %>
<% end %>

<p>コメント</p>

<% @comments.each do |comment| %>
  <%= link_to comment.user.name, comment.user %>
  <%= comment.content %><br>
<% end %>

<%= form_for [@micropost, @comment] do |f| %>
  <%= f.text_field :content %>
  <%= f.hidden_field :micropost_id, value: @micropost.id %>
  <%= f.submit 'コメントする' %>
<% end %>