config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'hoges/index'
  get 'hoges/new'
  post 'hoges/create',as:"hoges"
  get 'hoges/:id' => 'hoges#show', as: 'hoge'
  get 'likes/create'
  get 'likes/destroy'
  get 'sessions/new'
  get 'users/new'
  get 'persons/new'
  root 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get 'microposts/index'
  resources :microposts do
    resources :comments, only: [:create]
  end
  get '/posts' => 'post#index'
  get 'posts/index'
  get '/signup' => 'users#new'
  post '/singup' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :microposts, only:[:create, :destroy]
  resources :relationships, only:[:create,:destroy]
  resources :likes, only: [:create, :destroy]
end 

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :microposts, optional: true
end

app/models/hoge.rb
class Hoge < ApplicationRecord
  validates :name, presence: true
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :micropost
    counter_culture :micropost
    validates :user_id, presence: true
    validates :micropost_id, presence: true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate :picture_size
  has_many :likes, dependent: :destroy
  has_many :iine_users, through: :likes, source: :user
  has_many :comments

  def iine(user)
    likes.create(user_id: user.id)
  end

  def uniine(user)
    likes.find_by(user_id: user.id).destroy
  end

  def iine?(user)
    iine_users.include?(user)
  end

  private

    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor:remember_token, :activation_token
  has_many :microposts,dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                          foreign_key: "follower_id",
                          dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                          foreign_key: "followed_id",
                          dependent: :destroy
  has_many :following, through: :active_relationships,source: :followed
  has_many :followers, through: :passive_relationships,source: :follower                      
  has_many :likes, dependent: :destroy
  
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 },allow_nil: true


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                              BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def feed
    Micropost.where("user_id IN (:following_ids) OR user_id = :user_id",
    following_ids: following_ids, user_id: id)  
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

 private

  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/hoges_controller.rb
class HogesController < ApplicationController
  def index
    @hoges = Hoge.all
  end

  def show
    @hoge = Hoge.find(params[:id])
  end

  def new
    @hoge = Hoge.new
  end

  def create
    @hoge = Hoge.new(hoges_params)
    if @hoge.save
      flash[:hoge] = "投稿完了！"
      redirect_to :action => "index"
    else
      render :action => "new"
    end
  end

  def hoges_params
    params.require(:hoge).permit(:name, :content)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :logged_in_user
  
  def create
    @micropost = Micropost.find(params[:micropost_id])
    unless @micropost.iine?(current_user)
    @micropost.iine(current_user)
    @micropost.reload
      respond_to do |format|
        format.html { redirect_to request.referrer || root_url }
        format.js
      end
    end
  end

  def destroy
    @micropost = Like.find(params[:id]).micropost
    if @micropost.iine?(current_user)
    @micropost.uniine(current_user)
    @micropost.reload
      respond_to do |format|
        format.html { redirect_to request.referrer || root_url}
        format.js
      end
    end
  end
end

app/controllers/post_controller.rb
# frozen_string_literal: true

class PostController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = '')
    base_title = ' Ruby on Rails Tutorial Sample App'
    if page_title.empty?
      base_title
    else
      page_title + ' |' + base_title
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hoges_helper.rb
module HogesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/persons_helper.rb
# frozen_string_literal: true

module PersonsHelper
end

app/helpers/post_helper.rb
# frozen_string_literal: true

module PostHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def current_user?(user)
    user == current_user
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id:user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def gravatar_for(user, options = { size:80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar',size:50)
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application',
                           'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
        <li><%= link_to "Users", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Accout <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%=link_to "Profile", current_user %></li>
            <li><%=link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out",logout_path, method: :delete %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/head' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type,message|%>
       <%= content_tag(:div,message,class: "alert alert-#{message_type}")%>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params)if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% @microposts.each do |micropost| %>
  <div class="micropost">
    <%= link_to micropost.user.name, micropost.user %>
    <%= link_to (micropost_path(micropost)) do %>
      <%= micropost.content %>
    <% end %>
    <% if current_user.id == micropost.user.id %>
      <%= link_to  "削除", "microposts/#{micropost.id}", method: :delete %>
    <% end %>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for (@micropost) do |f| %>
 <%= render 'shared/error_messages', object:f.object %>
 <div class="filed">
   <%= f.text_area :content, placeholder: "Compose new micropost..." %>
 </div>
 <%= f.submit "Post", class:"btn btn-primary"%>
 <span class="picture">
   <%= f.file_field :picture, accept:'image/jpeg,image/gif,image/png' %>
 </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_microposts_search_form.html.erb
<%= search_form_for @q, url: @url do |f| %>
  <%= f.label :content_cont, "記事内検索" %>
  <div class="input-group">
    <%= f.text_field :content_cont, placeholder: "キーワードを入力してください",
                                   class: 'form-control' %>
    <span class="input-group-btn">
      <%= f.submit '検索', class: "btn btn-primary"%>
    </span>                               
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user)%>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user)%>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size:50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to  "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count,"micropost") %></span>